spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://120.79.253.92/mmall?characterEncoding=utf-8&useSSL=false
server:
    port: 9000


mybatis:
  mapper-locations: classpath:mappers/*.xml

ftp:
  ip: 192.168.10.105
  user: zzh
  password: 123456
  prefix: http://img.happymmall.com/
  port: 21

alipay:
  callbackurl: http://qaa6se.natappfree.cc/order/alipay_callback.do