spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/mmall?characterEncoding=utf-8&useSSL=false
server:
 # servlet:
  #  context-path: /mmall
  port: 9000

mybatis:
  mapper-locations: classpath:mappers/*.xml

ftp:
  ip: 192.168.10.105
  user: zzh
  password: 123456
  prefix: ftp://localhost/
  port: 21

alipay:
  callbackurl: http://qaa6se.natappfree.cc/order/alipay_callback.do

